GET http://localhost:3000/users/
###

GET http://localhost:3000/users/2
###

//crear
POST http://localhost:3000/users/
Content-Type: application/json 

{
  "username": "Denis",
  "password": "bike123",
  "email": "bike@gmail.com"
}

###actualizar
PUT http://localhost:3000/users/4
Content-Type: application/json

{
  "username": "Dennis",
  "password": "246810"

  
  //para actualizar el usuario
}

###
POST  http://localhost:3000/users/login
Content-Type: application/json

{
  "username": "Dennis",
  "password": "246810"

  
  //para LOGIN
}

###
DELETE http://localhost:3000/users/1
