POST http://localhost:3000/auth/login
Content-Type: application/json

{

    "email": "jet@gmail.com",
    "password": "j1229"
}




###

GET http://localhost:3000/users/protected
Content-Type: application/json
Authorization: Bearer eyJhbGciOiJIUzI1NiIsInR5cCI6IkpXVCJ9.eyJpZCI6NCwiaXNfYWRtaW4iOjAsImlhdCI6MTczNDAyMzM1NywiZXhwIjoxNzM0MDIzNjU3fQ.4rpfzVPaJ3MooYhpQWdpFwLiiQTbS1TsnsZMrGz3tV0