GET http://localhost:3000/users
Content-Type: application/json
Authorization: Bearer eyJhbGciOiJIUzI1NiIsInR5cCI6IkpXVCJ9.eyJpZCI6MiwiaXNfYWRtaW4iOjEsImlhdCI6MTczNDAyMTU4MSwiZXhwIjoxNzM0MDIxODgxfQ.4LlpawdGj6PbQdPIyflnYO-Jg1PxPGmMtvo_U0GfYfM

###Mostar usuario por ID
GET http://localhost:3000/users/2
Content-Type: application/json
Authorization: Bearer eyJhbGciOiJIUzI1NiIsInR5cCI6IkpXVCJ9.eyJpZCI6MiwiaXNfYWRtaW4iOjEsImlhdCI6MTczNDAyMTU4MSwiZXhwIjoxNzM0MDIxODgxfQ.4LlpawdGj6PbQdPIyflnYO-Jg1PxPGmMtvo_U0GfYfM

### Agregar
POST http://localhost:3000/users
Content-Type: application/json
Authorization: Bearer eyJhbGciOiJIUzI1NiIsInR5cCI6IkpXVCJ9.eyJpZCI6NCwiaXNfYWRtaW4iOjAsImlhdCI6MTczNDAyMzM1NywiZXhwIjoxNzM0MDIzNjU3fQ.4rpfzVPaJ3MooYhpQWdpFwLiiQTbS1TsnsZMrGz3tV0

{
  "first_name":" Logan",
  "last_name": "Henderson",
  "email": "logan@gmail.com",
  "password": "H1229"
}

### EDITAR
PUT http://localhost:3000/users/5
Content-Type: application/json

{
  "first_name":" Marly",
  "last_name": "Ignacio",
  "email": "marly@gmail.com"
}

###Elimimar usuario
DELETE http://localhost:3000/users/4