GET http://localhost:3000/users

###Mostar usuario por ID
GET http://localhost:3000/users/1

### Agregar
POST http://localhost:3000/users
Content-Type: application/json

{
  "first_name":" Maria",
  "last_name": "Ignacio",
  "email": "mari@gmail.com",
  "password": "m1227"
}

### EDITAR
PUT http://localhost:3000/users/5
Content-Type: application/json

{
  "first_name":" Marly",
  "last_name": "Ignacio",
  "email": "marly@gmail.com"
}

###Elimimar usuario
DELETE http://localhost:3000/users/4